name: Bondex Remote CI

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build All Modules (Client & Admin)
      run: ./gradlew assembleRelease

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bondex-apks
        path: |
          app/build/outputs/apk/release/*.apk
          admin/build/outputs/apk/release/*.apk

    - name: Release APKs
      uses: andelf/nightly-release@main
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: bondex-remote-v1
        name: 'Bondex Remote Control Release'
        draft: false
        prerelease: false
        body: |
          Automated Build for Bondex Remote.
          - app-release.apk: Client (Target)
          - admin-release.apk: Controller (Admin)
        files: |
          app/build/outputs/apk/release/app-release.apk
          admin/build/outputs/apk/release/admin-release.apk
